import { ThemeProvider } from "@/components/themeProvider";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/context/authContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en" className={`h-full antialiased`}>
      <body className="h-screen flex gap-5 flex-col">
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <div className="px-8 flex-1">{children}</div>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
